# Generated by Django 4.0.5 on 2022-06-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produo',
            new_name='Produto',
        ),
    ]
